// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: cursor_usage.proto

// Cursor dashboard/usage RPCs. These messages are transported to
// aiserver.v1.DashboardService and aiserver.v1.AiService, but are declared in a
// separate proto file (kept OUT of gen/cursor/) because the core extraction
// scoped the main cursor.proto to chat/agent flows. Wire format is preserved
// (all field numbers and types match Cursor 3.10.20 exactly).

package usagepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCurrentPeriodUsageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        *int32                 `protobuf:"varint,1,opt,name=team_id,json=teamId,proto3,oneof" json:"team_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentPeriodUsageRequest) Reset() {
	*x = GetCurrentPeriodUsageRequest{}
	mi := &file_cursor_usage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentPeriodUsageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentPeriodUsageRequest) ProtoMessage() {}

func (x *GetCurrentPeriodUsageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cursor_usage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentPeriodUsageRequest.ProtoReflect.Descriptor instead.
func (*GetCurrentPeriodUsageRequest) Descriptor() ([]byte, []int) {
	return file_cursor_usage_proto_rawDescGZIP(), []int{0}
}

func (x *GetCurrentPeriodUsageRequest) GetTeamId() int32 {
	if x != nil && x.TeamId != nil {
		return *x.TeamId
	}
	return 0
}

type GetCurrentPeriodUsageResponse struct {
	state                            protoimpl.MessageState                              `protogen:"open.v1"`
	BillingCycleStart                int64                                               `protobuf:"varint,1,opt,name=billing_cycle_start,json=billingCycleStart,proto3" json:"billing_cycle_start,omitempty"`
	BillingCycleEnd                  int64                                               `protobuf:"varint,2,opt,name=billing_cycle_end,json=billingCycleEnd,proto3" json:"billing_cycle_end,omitempty"`
	PlanUsage                        *GetCurrentPeriodUsageResponse_PlanUsage            `protobuf:"bytes,3,opt,name=plan_usage,json=planUsage,proto3" json:"plan_usage,omitempty"`
	SpendLimitUsage                  *GetCurrentPeriodUsageResponse_SpendLimitUsage      `protobuf:"bytes,4,opt,name=spend_limit_usage,json=spendLimitUsage,proto3" json:"spend_limit_usage,omitempty"`
	DisplayThreshold                 *int32                                              `protobuf:"varint,5,opt,name=display_threshold,json=displayThreshold,proto3,oneof" json:"display_threshold,omitempty"`
	Enabled                          bool                                                `protobuf:"varint,6,opt,name=enabled,proto3" json:"enabled,omitempty"`
	DisplayMessage                   string                                              `protobuf:"bytes,7,opt,name=display_message,json=displayMessage,proto3" json:"display_message,omitempty"`
	FreeBestOfNPromotion             *GetCurrentPeriodUsageResponse_FreeBestOfNPromotion `protobuf:"bytes,8,opt,name=free_best_of_n_promotion,json=freeBestOfNPromotion,proto3,oneof" json:"free_best_of_n_promotion,omitempty"`
	AutoModelSelectedDisplayMessage  *string                                             `protobuf:"bytes,11,opt,name=auto_model_selected_display_message,json=autoModelSelectedDisplayMessage,proto3,oneof" json:"auto_model_selected_display_message,omitempty"`
	NamedModelSelectedDisplayMessage *string                                             `protobuf:"bytes,12,opt,name=named_model_selected_display_message,json=namedModelSelectedDisplayMessage,proto3,oneof" json:"named_model_selected_display_message,omitempty"`
	AutoBucketModels                 []string                                            `protobuf:"bytes,13,rep,name=auto_bucket_models,json=autoBucketModels,proto3" json:"auto_bucket_models,omitempty"`
	unknownFields                    protoimpl.UnknownFields
	sizeCache                        protoimpl.SizeCache
}

func (x *GetCurrentPeriodUsageResponse) Reset() {
	*x = GetCurrentPeriodUsageResponse{}
	mi := &file_cursor_usage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentPeriodUsageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentPeriodUsageResponse) ProtoMessage() {}

func (x *GetCurrentPeriodUsageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cursor_usage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentPeriodUsageResponse.ProtoReflect.Descriptor instead.
func (*GetCurrentPeriodUsageResponse) Descriptor() ([]byte, []int) {
	return file_cursor_usage_proto_rawDescGZIP(), []int{1}
}

func (x *GetCurrentPeriodUsageResponse) GetBillingCycleStart() int64 {
	if x != nil {
		return x.BillingCycleStart
	}
	return 0
}

func (x *GetCurrentPeriodUsageResponse) GetBillingCycleEnd() int64 {
	if x != nil {
		return x.BillingCycleEnd
	}
	return 0
}

func (x *GetCurrentPeriodUsageResponse) GetPlanUsage() *GetCurrentPeriodUsageResponse_PlanUsage {
	if x != nil {
		return x.PlanUsage
	}
	return nil
}

func (x *GetCurrentPeriodUsageResponse) GetSpendLimitUsage() *GetCurrentPeriodUsageResponse_SpendLimitUsage {
	if x != nil {
		return x.SpendLimitUsage
	}
	return nil
}

func (x *GetCurrentPeriodUsageResponse) GetDisplayThreshold() int32 {
	if x != nil && x.DisplayThreshold != nil {
		return *x.DisplayThreshold
	}
	return 0
}

func (x *GetCurrentPeriodUsageResponse) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *GetCurrentPeriodUsageResponse) GetDisplayMessage() string {
	if x != nil {
		return x.DisplayMessage
	}
	return ""
}

func (x *GetCurrentPeriodUsageResponse) GetFreeBestOfNPromotion() *GetCurrentPeriodUsageResponse_FreeBestOfNPromotion {
	if x != nil {
		return x.FreeBestOfNPromotion
	}
	return nil
}

func (x *GetCurrentPeriodUsageResponse) GetAutoModelSelectedDisplayMessage() string {
	if x != nil && x.AutoModelSelectedDisplayMessage != nil {
		return *x.AutoModelSelectedDisplayMessage
	}
	return ""
}

func (x *GetCurrentPeriodUsageResponse) GetNamedModelSelectedDisplayMessage() string {
	if x != nil && x.NamedModelSelectedDisplayMessage != nil {
		return *x.NamedModelSelectedDisplayMessage
	}
	return ""
}

func (x *GetCurrentPeriodUsageResponse) GetAutoBucketModels() []string {
	if x != nil {
		return x.AutoBucketModels
	}
	return nil
}

type GetCurrentBillingCycleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        *int32                 `protobuf:"varint,1,opt,name=team_id,json=teamId,proto3,oneof" json:"team_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentBillingCycleRequest) Reset() {
	*x = GetCurrentBillingCycleRequest{}
	mi := &file_cursor_usage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentBillingCycleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentBillingCycleRequest) ProtoMessage() {}

func (x *GetCurrentBillingCycleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cursor_usage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentBillingCycleRequest.ProtoReflect.Descriptor instead.
func (*GetCurrentBillingCycleRequest) Descriptor() ([]byte, []int) {
	return file_cursor_usage_proto_rawDescGZIP(), []int{2}
}

func (x *GetCurrentBillingCycleRequest) GetTeamId() int32 {
	if x != nil && x.TeamId != nil {
		return *x.TeamId
	}
	return 0
}

type GetCurrentBillingCycleResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	StartDateEpochMillis int64                  `protobuf:"varint,1,opt,name=start_date_epoch_millis,json=startDateEpochMillis,proto3" json:"start_date_epoch_millis,omitempty"`
	EndDateEpochMillis   int64                  `protobuf:"varint,2,opt,name=end_date_epoch_millis,json=endDateEpochMillis,proto3" json:"end_date_epoch_millis,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetCurrentBillingCycleResponse) Reset() {
	*x = GetCurrentBillingCycleResponse{}
	mi := &file_cursor_usage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentBillingCycleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentBillingCycleResponse) ProtoMessage() {}

func (x *GetCurrentBillingCycleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cursor_usage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentBillingCycleResponse.ProtoReflect.Descriptor instead.
func (*GetCurrentBillingCycleResponse) Descriptor() ([]byte, []int) {
	return file_cursor_usage_proto_rawDescGZIP(), []int{3}
}

func (x *GetCurrentBillingCycleResponse) GetStartDateEpochMillis() int64 {
	if x != nil {
		return x.StartDateEpochMillis
	}
	return 0
}

func (x *GetCurrentBillingCycleResponse) GetEndDateEpochMillis() int64 {
	if x != nil {
		return x.EndDateEpochMillis
	}
	return 0
}

type GetAggregatedUsageEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        int32                  `protobuf:"varint,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	StartDate     *int64                 `protobuf:"varint,2,opt,name=start_date,json=startDate,proto3,oneof" json:"start_date,omitempty"`
	EndDate       *int64                 `protobuf:"varint,3,opt,name=end_date,json=endDate,proto3,oneof" json:"end_date,omitempty"`
	UserId        *int32                 `protobuf:"varint,4,opt,name=user_id,json=userId,proto3,oneof" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAggregatedUsageEventsRequest) Reset() {
	*x = GetAggregatedUsageEventsRequest{}
	mi := &file_cursor_usage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAggregatedUsageEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAggregatedUsageEventsRequest) ProtoMessage() {}

func (x *GetAggregatedUsageEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cursor_usage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAggregatedUsageEventsRequest.ProtoReflect.Descriptor instead.
func (*GetAggregatedUsageEventsRequest) Descriptor() ([]byte, []int) {
	return file_cursor_usage_proto_rawDescGZIP(), []int{4}
}

func (x *GetAggregatedUsageEventsRequest) GetTeamId() int32 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *GetAggregatedUsageEventsRequest) GetStartDate() int64 {
	if x != nil && x.StartDate != nil {
		return *x.StartDate
	}
	return 0
}

func (x *GetAggregatedUsageEventsRequest) GetEndDate() int64 {
	if x != nil && x.EndDate != nil {
		return *x.EndDate
	}
	return 0
}

func (x *GetAggregatedUsageEventsRequest) GetUserId() int32 {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return 0
}

type GetAggregatedUsageEventsResponse struct {
	state                 protoimpl.MessageState                                    `protogen:"open.v1"`
	Aggregations          []*GetAggregatedUsageEventsResponse_ModelUsageAggregation `protobuf:"bytes,1,rep,name=aggregations,proto3" json:"aggregations,omitempty"`
	TotalInputTokens      int64                                                     `protobuf:"varint,2,opt,name=total_input_tokens,json=totalInputTokens,proto3" json:"total_input_tokens,omitempty"`
	TotalOutputTokens     int64                                                     `protobuf:"varint,3,opt,name=total_output_tokens,json=totalOutputTokens,proto3" json:"total_output_tokens,omitempty"`
	TotalCacheWriteTokens int64                                                     `protobuf:"varint,4,opt,name=total_cache_write_tokens,json=totalCacheWriteTokens,proto3" json:"total_cache_write_tokens,omitempty"`
	TotalCacheReadTokens  int64                                                     `protobuf:"varint,5,opt,name=total_cache_read_tokens,json=totalCacheReadTokens,proto3" json:"total_cache_read_tokens,omitempty"`
	TotalCostCents        float64                                                   `protobuf:"fixed64,6,opt,name=total_cost_cents,json=totalCostCents,proto3" json:"total_cost_cents,omitempty"`
	PercentOfBurstUsed    float64                                                   `protobuf:"fixed64,7,opt,name=percent_of_burst_used,json=percentOfBurstUsed,proto3" json:"percent_of_burst_used,omitempty"`
	TotalRequestCost      *float64                                                  `protobuf:"fixed64,8,opt,name=total_request_cost,json=totalRequestCost,proto3,oneof" json:"total_request_cost,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GetAggregatedUsageEventsResponse) Reset() {
	*x = GetAggregatedUsageEventsResponse{}
	mi := &file_cursor_usage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAggregatedUsageEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAggregatedUsageEventsResponse) ProtoMessage() {}

func (x *GetAggregatedUsageEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cursor_usage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAggregatedUsageEventsResponse.ProtoReflect.Descriptor instead.
func (*GetAggregatedUsageEventsResponse) Descriptor() ([]byte, []int) {
	return file_cursor_usage_proto_rawDescGZIP(), []int{5}
}

func (x *GetAggregatedUsageEventsResponse) GetAggregations() []*GetAggregatedUsageEventsResponse_ModelUsageAggregation {
	if x != nil {
		return x.Aggregations
	}
	return nil
}

func (x *GetAggregatedUsageEventsResponse) GetTotalInputTokens() int64 {
	if x != nil {
		return x.TotalInputTokens
	}
	return 0
}

func (x *GetAggregatedUsageEventsResponse) GetTotalOutputTokens() int64 {
	if x != nil {
		return x.TotalOutputTokens
	}
	return 0
}

func (x *GetAggregatedUsageEventsResponse) GetTotalCacheWriteTokens() int64 {
	if x != nil {
		return x.TotalCacheWriteTokens
	}
	return 0
}

func (x *GetAggregatedUsageEventsResponse) GetTotalCacheReadTokens() int64 {
	if x != nil {
		return x.TotalCacheReadTokens
	}
	return 0
}

func (x *GetAggregatedUsageEventsResponse) GetTotalCostCents() float64 {
	if x != nil {
		return x.TotalCostCents
	}
	return 0
}

func (x *GetAggregatedUsageEventsResponse) GetPercentOfBurstUsed() float64 {
	if x != nil {
		return x.PercentOfBurstUsed
	}
	return 0
}

func (x *GetAggregatedUsageEventsResponse) GetTotalRequestCost() float64 {
	if x != nil && x.TotalRequestCost != nil {
		return *x.TotalRequestCost
	}
	return 0
}

type GetUsageBasedPremiumRequestsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        int32                  `protobuf:"varint,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsageBasedPremiumRequestsRequest) Reset() {
	*x = GetUsageBasedPremiumRequestsRequest{}
	mi := &file_cursor_usage_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsageBasedPremiumRequestsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsageBasedPremiumRequestsRequest) ProtoMessage() {}

func (x *GetUsageBasedPremiumRequestsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cursor_usage_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsageBasedPremiumRequestsRequest.ProtoReflect.Descriptor instead.
func (*GetUsageBasedPremiumRequestsRequest) Descriptor() ([]byte, []int) {
	return file_cursor_usage_proto_rawDescGZIP(), []int{6}
}

func (x *GetUsageBasedPremiumRequestsRequest) GetTeamId() int32 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

type GetUsageBasedPremiumRequestsResponse struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	UsageBasedPremiumRequests bool                   `protobuf:"varint,1,opt,name=usage_based_premium_requests,json=usageBasedPremiumRequests,proto3" json:"usage_based_premium_requests,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *GetUsageBasedPremiumRequestsResponse) Reset() {
	*x = GetUsageBasedPremiumRequestsResponse{}
	mi := &file_cursor_usage_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsageBasedPremiumRequestsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsageBasedPremiumRequestsResponse) ProtoMessage() {}

func (x *GetUsageBasedPremiumRequestsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cursor_usage_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsageBasedPremiumRequestsResponse.ProtoReflect.Descriptor instead.
func (*GetUsageBasedPremiumRequestsResponse) Descriptor() ([]byte, []int) {
	return file_cursor_usage_proto_rawDescGZIP(), []int{7}
}

func (x *GetUsageBasedPremiumRequestsResponse) GetUsageBasedPremiumRequests() bool {
	if x != nil {
		return x.UsageBasedPremiumRequests
	}
	return false
}

type GetHardLimitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        *int32                 `protobuf:"varint,1,opt,name=team_id,json=teamId,proto3,oneof" json:"team_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHardLimitRequest) Reset() {
	*x = GetHardLimitRequest{}
	mi := &file_cursor_usage_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHardLimitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHardLimitRequest) ProtoMessage() {}

func (x *GetHardLimitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cursor_usage_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHardLimitRequest.ProtoReflect.Descriptor instead.
func (*GetHardLimitRequest) Descriptor() ([]byte, []int) {
	return file_cursor_usage_proto_rawDescGZIP(), []int{8}
}

func (x *GetHardLimitRequest) GetTeamId() int32 {
	if x != nil && x.TeamId != nil {
		return *x.TeamId
	}
	return 0
}

type GetHardLimitResponse struct {
	state                                protoimpl.MessageState `protogen:"open.v1"`
	HardLimit                            int32                  `protobuf:"varint,1,opt,name=hard_limit,json=hardLimit,proto3" json:"hard_limit,omitempty"`
	NoUsageBasedAllowed                  bool                   `protobuf:"varint,2,opt,name=no_usage_based_allowed,json=noUsageBasedAllowed,proto3" json:"no_usage_based_allowed,omitempty"`
	HardLimitPerUser                     *int32                 `protobuf:"varint,3,opt,name=hard_limit_per_user,json=hardLimitPerUser,proto3,oneof" json:"hard_limit_per_user,omitempty"`
	PerUserMonthlyLimitDollars           int32                  `protobuf:"varint,4,opt,name=per_user_monthly_limit_dollars,json=perUserMonthlyLimitDollars,proto3" json:"per_user_monthly_limit_dollars,omitempty"`
	IsDynamicTeamLimit                   bool                   `protobuf:"varint,5,opt,name=is_dynamic_team_limit,json=isDynamicTeamLimit,proto3" json:"is_dynamic_team_limit,omitempty"`
	HasPendingSetupOnboardingCreditClaim bool                   `protobuf:"varint,6,opt,name=has_pending_setup_onboarding_credit_claim,json=hasPendingSetupOnboardingCreditClaim,proto3" json:"has_pending_setup_onboarding_credit_claim,omitempty"`
	IsSetupPromoActive                   bool                   `protobuf:"varint,7,opt,name=is_setup_promo_active,json=isSetupPromoActive,proto3" json:"is_setup_promo_active,omitempty"`
	SetupPromoAmountCents                *int32                 `protobuf:"varint,8,opt,name=setup_promo_amount_cents,json=setupPromoAmountCents,proto3,oneof" json:"setup_promo_amount_cents,omitempty"`
	SetupPromoCreditValidityDays         *int32                 `protobuf:"varint,9,opt,name=setup_promo_credit_validity_days,json=setupPromoCreditValidityDays,proto3,oneof" json:"setup_promo_credit_validity_days,omitempty"`
	unknownFields                        protoimpl.UnknownFields
	sizeCache                            protoimpl.SizeCache
}

func (x *GetHardLimitResponse) Reset() {
	*x = GetHardLimitResponse{}
	mi := &file_cursor_usage_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHardLimitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHardLimitResponse) ProtoMessage() {}

func (x *GetHardLimitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cursor_usage_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHardLimitResponse.ProtoReflect.Descriptor instead.
func (*GetHardLimitResponse) Descriptor() ([]byte, []int) {
	return file_cursor_usage_proto_rawDescGZIP(), []int{9}
}

func (x *GetHardLimitResponse) GetHardLimit() int32 {
	if x != nil {
		return x.HardLimit
	}
	return 0
}

func (x *GetHardLimitResponse) GetNoUsageBasedAllowed() bool {
	if x != nil {
		return x.NoUsageBasedAllowed
	}
	return false
}

func (x *GetHardLimitResponse) GetHardLimitPerUser() int32 {
	if x != nil && x.HardLimitPerUser != nil {
		return *x.HardLimitPerUser
	}
	return 0
}

func (x *GetHardLimitResponse) GetPerUserMonthlyLimitDollars() int32 {
	if x != nil {
		return x.PerUserMonthlyLimitDollars
	}
	return 0
}

func (x *GetHardLimitResponse) GetIsDynamicTeamLimit() bool {
	if x != nil {
		return x.IsDynamicTeamLimit
	}
	return false
}

func (x *GetHardLimitResponse) GetHasPendingSetupOnboardingCreditClaim() bool {
	if x != nil {
		return x.HasPendingSetupOnboardingCreditClaim
	}
	return false
}

func (x *GetHardLimitResponse) GetIsSetupPromoActive() bool {
	if x != nil {
		return x.IsSetupPromoActive
	}
	return false
}

func (x *GetHardLimitResponse) GetSetupPromoAmountCents() int32 {
	if x != nil && x.SetupPromoAmountCents != nil {
		return *x.SetupPromoAmountCents
	}
	return 0
}

func (x *GetHardLimitResponse) GetSetupPromoCreditValidityDays() int32 {
	if x != nil && x.SetupPromoCreditValidityDays != nil {
		return *x.SetupPromoCreditValidityDays
	}
	return 0
}

type ActiveCreditGrant struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	GrantId            string                 `protobuf:"bytes,1,opt,name=grant_id,json=grantId,proto3" json:"grant_id,omitempty"`
	TotalCents         int64                  `protobuf:"varint,2,opt,name=total_cents,json=totalCents,proto3" json:"total_cents,omitempty"`
	RemainingCents     int64                  `protobuf:"varint,3,opt,name=remaining_cents,json=remainingCents,proto3" json:"remaining_cents,omitempty"`
	ExpiresAtMs        int64                  `protobuf:"varint,4,opt,name=expires_at_ms,json=expiresAtMs,proto3" json:"expires_at_ms,omitempty"`
	AllowedModelIds    []string               `protobuf:"bytes,5,rep,name=allowed_model_ids,json=allowedModelIds,proto3" json:"allowed_model_ids,omitempty"`
	AllowedModelTags   []string               `protobuf:"bytes,6,rep,name=allowed_model_tags,json=allowedModelTags,proto3" json:"allowed_model_tags,omitempty"`
	GrantType          string                 `protobuf:"bytes,7,opt,name=grant_type,json=grantType,proto3" json:"grant_type,omitempty"`
	SlownessMs         *int32                 `protobuf:"varint,8,opt,name=slowness_ms,json=slownessMs,proto3,oneof" json:"slowness_ms,omitempty"`
	Source             *string                `protobuf:"bytes,9,opt,name=source,proto3,oneof" json:"source,omitempty"`
	CampaignName       *string                `protobuf:"bytes,10,opt,name=campaign_name,json=campaignName,proto3,oneof" json:"campaign_name,omitempty"`
	ShowInClient       bool                   `protobuf:"varint,11,opt,name=show_in_client,json=showInClient,proto3" json:"show_in_client,omitempty"`
	AllowedClientTypes []string               `protobuf:"bytes,12,rep,name=allowed_client_types,json=allowedClientTypes,proto3" json:"allowed_client_types,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ActiveCreditGrant) Reset() {
	*x = ActiveCreditGrant{}
	mi := &file_cursor_usage_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActiveCreditGrant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActiveCreditGrant) ProtoMessage() {}

func (x *ActiveCreditGrant) ProtoReflect() protoreflect.Message {
	mi := &file_cursor_usage_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActiveCreditGrant.ProtoReflect.Descriptor instead.
func (*ActiveCreditGrant) Descriptor() ([]byte, []int) {
	return file_cursor_usage_proto_rawDescGZIP(), []int{10}
}

func (x *ActiveCreditGrant) GetGrantId() string {
	if x != nil {
		return x.GrantId
	}
	return ""
}

func (x *ActiveCreditGrant) GetTotalCents() int64 {
	if x != nil {
		return x.TotalCents
	}
	return 0
}

func (x *ActiveCreditGrant) GetRemainingCents() int64 {
	if x != nil {
		return x.RemainingCents
	}
	return 0
}

func (x *ActiveCreditGrant) GetExpiresAtMs() int64 {
	if x != nil {
		return x.ExpiresAtMs
	}
	return 0
}

func (x *ActiveCreditGrant) GetAllowedModelIds() []string {
	if x != nil {
		return x.AllowedModelIds
	}
	return nil
}

func (x *ActiveCreditGrant) GetAllowedModelTags() []string {
	if x != nil {
		return x.AllowedModelTags
	}
	return nil
}

func (x *ActiveCreditGrant) GetGrantType() string {
	if x != nil {
		return x.GrantType
	}
	return ""
}

func (x *ActiveCreditGrant) GetSlownessMs() int32 {
	if x != nil && x.SlownessMs != nil {
		return *x.SlownessMs
	}
	return 0
}

func (x *ActiveCreditGrant) GetSource() string {
	if x != nil && x.Source != nil {
		return *x.Source
	}
	return ""
}

func (x *ActiveCreditGrant) GetCampaignName() string {
	if x != nil && x.CampaignName != nil {
		return *x.CampaignName
	}
	return ""
}

func (x *ActiveCreditGrant) GetShowInClient() bool {
	if x != nil {
		return x.ShowInClient
	}
	return false
}

func (x *ActiveCreditGrant) GetAllowedClientTypes() []string {
	if x != nil {
		return x.AllowedClientTypes
	}
	return nil
}

type GetUsageLimitStatusAndActiveGrantsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsageLimitStatusAndActiveGrantsRequest) Reset() {
	*x = GetUsageLimitStatusAndActiveGrantsRequest{}
	mi := &file_cursor_usage_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsageLimitStatusAndActiveGrantsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsageLimitStatusAndActiveGrantsRequest) ProtoMessage() {}

func (x *GetUsageLimitStatusAndActiveGrantsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cursor_usage_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsageLimitStatusAndActiveGrantsRequest.ProtoReflect.Descriptor instead.
func (*GetUsageLimitStatusAndActiveGrantsRequest) Descriptor() ([]byte, []int) {
	return file_cursor_usage_proto_rawDescGZIP(), []int{11}
}

type GetUsageLimitStatusAndActiveGrantsResponse struct {
	state                  protoimpl.MessageState                                             `protogen:"open.v1"`
	UsageLimitPolicyStatus *GetUsageLimitStatusAndActiveGrantsResponse_UsageLimitPolicyStatus `protobuf:"bytes,1,opt,name=usage_limit_policy_status,json=usageLimitPolicyStatus,proto3" json:"usage_limit_policy_status,omitempty"`
	ActiveGrants           []*ActiveCreditGrant                                               `protobuf:"bytes,2,rep,name=active_grants,json=activeGrants,proto3" json:"active_grants,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetUsageLimitStatusAndActiveGrantsResponse) Reset() {
	*x = GetUsageLimitStatusAndActiveGrantsResponse{}
	mi := &file_cursor_usage_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsageLimitStatusAndActiveGrantsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsageLimitStatusAndActiveGrantsResponse) ProtoMessage() {}

func (x *GetUsageLimitStatusAndActiveGrantsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cursor_usage_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsageLimitStatusAndActiveGrantsResponse.ProtoReflect.Descriptor instead.
func (*GetUsageLimitStatusAndActiveGrantsResponse) Descriptor() ([]byte, []int) {
	return file_cursor_usage_proto_rawDescGZIP(), []int{12}
}

func (x *GetUsageLimitStatusAndActiveGrantsResponse) GetUsageLimitPolicyStatus() *GetUsageLimitStatusAndActiveGrantsResponse_UsageLimitPolicyStatus {
	if x != nil {
		return x.UsageLimitPolicyStatus
	}
	return nil
}

func (x *GetUsageLimitStatusAndActiveGrantsResponse) GetActiveGrants() []*ActiveCreditGrant {
	if x != nil {
		return x.ActiveGrants
	}
	return nil
}

type GetMeRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TeamId             *int32                 `protobuf:"varint,1,opt,name=team_id,json=teamId,proto3,oneof" json:"team_id,omitempty"`
	SourceSiteHostname *string                `protobuf:"bytes,2,opt,name=source_site_hostname,json=sourceSiteHostname,proto3,oneof" json:"source_site_hostname,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetMeRequest) Reset() {
	*x = GetMeRequest{}
	mi := &file_cursor_usage_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeRequest) ProtoMessage() {}

func (x *GetMeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cursor_usage_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeRequest.ProtoReflect.Descriptor instead.
func (*GetMeRequest) Descriptor() ([]byte, []int) {
	return file_cursor_usage_proto_rawDescGZIP(), []int{13}
}

func (x *GetMeRequest) GetTeamId() int32 {
	if x != nil && x.TeamId != nil {
		return *x.TeamId
	}
	return 0
}

func (x *GetMeRequest) GetSourceSiteHostname() string {
	if x != nil && x.SourceSiteHostname != nil {
		return *x.SourceSiteHostname
	}
	return ""
}

type GetMeResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AuthId           string                 `protobuf:"bytes,1,opt,name=auth_id,json=authId,proto3" json:"auth_id,omitempty"`
	UserId           int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email            *string                `protobuf:"bytes,3,opt,name=email,proto3,oneof" json:"email,omitempty"`
	FirstName        *string                `protobuf:"bytes,4,opt,name=first_name,json=firstName,proto3,oneof" json:"first_name,omitempty"`
	LastName         *string                `protobuf:"bytes,5,opt,name=last_name,json=lastName,proto3,oneof" json:"last_name,omitempty"`
	WorkosId         *string                `protobuf:"bytes,6,opt,name=workos_id,json=workosId,proto3,oneof" json:"workos_id,omitempty"`
	TeamId           *int32                 `protobuf:"varint,7,opt,name=team_id,json=teamId,proto3,oneof" json:"team_id,omitempty"`
	CreatedAt        *string                `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3,oneof" json:"created_at,omitempty"`
	IsEnterpriseUser *bool                  `protobuf:"varint,9,opt,name=is_enterprise_user,json=isEnterpriseUser,proto3,oneof" json:"is_enterprise_user,omitempty"`
	TeamName         *string                `protobuf:"bytes,10,opt,name=team_name,json=teamName,proto3,oneof" json:"team_name,omitempty"`
	// email_domain_type is what the wire calls this; downstream surfaces it as
	// "sign_up_type" (e.g. "non-professional") for CPA account list display.
	EmailDomainType                          *string `protobuf:"bytes,11,opt,name=email_domain_type,json=emailDomainType,proto3,oneof" json:"email_domain_type,omitempty"`
	Country                                  *string `protobuf:"bytes,12,opt,name=country,proto3,oneof" json:"country,omitempty"`
	ProfilePictureUrl                        *string `protobuf:"bytes,13,opt,name=profile_picture_url,json=profilePictureUrl,proto3,oneof" json:"profile_picture_url,omitempty"`
	CursorReviewOnboardingUseCursorGithubApp *bool   `protobuf:"varint,14,opt,name=cursor_review_onboarding_use_cursor_github_app,json=cursorReviewOnboardingUseCursorGithubApp,proto3,oneof" json:"cursor_review_onboarding_use_cursor_github_app,omitempty"`
	OrganizationId                           *int64  `protobuf:"varint,15,opt,name=organization_id,json=organizationId,proto3,oneof" json:"organization_id,omitempty"`
	OrganizationPublicId                     *string `protobuf:"bytes,16,opt,name=organization_public_id,json=organizationPublicId,proto3,oneof" json:"organization_public_id,omitempty"`
	IsTeamAdmin                              *bool   `protobuf:"varint,17,opt,name=is_team_admin,json=isTeamAdmin,proto3,oneof" json:"is_team_admin,omitempty"`
	unknownFields                            protoimpl.UnknownFields
	sizeCache                                protoimpl.SizeCache
}

func (x *GetMeResponse) Reset() {
	*x = GetMeResponse{}
	mi := &file_cursor_usage_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeResponse) ProtoMessage() {}

func (x *GetMeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cursor_usage_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeResponse.ProtoReflect.Descriptor instead.
func (*GetMeResponse) Descriptor() ([]byte, []int) {
	return file_cursor_usage_proto_rawDescGZIP(), []int{14}
}

func (x *GetMeResponse) GetAuthId() string {
	if x != nil {
		return x.AuthId
	}
	return ""
}

func (x *GetMeResponse) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetMeResponse) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *GetMeResponse) GetFirstName() string {
	if x != nil && x.FirstName != nil {
		return *x.FirstName
	}
	return ""
}

func (x *GetMeResponse) GetLastName() string {
	if x != nil && x.LastName != nil {
		return *x.LastName
	}
	return ""
}

func (x *GetMeResponse) GetWorkosId() string {
	if x != nil && x.WorkosId != nil {
		return *x.WorkosId
	}
	return ""
}

func (x *GetMeResponse) GetTeamId() int32 {
	if x != nil && x.TeamId != nil {
		return *x.TeamId
	}
	return 0
}

func (x *GetMeResponse) GetCreatedAt() string {
	if x != nil && x.CreatedAt != nil {
		return *x.CreatedAt
	}
	return ""
}

func (x *GetMeResponse) GetIsEnterpriseUser() bool {
	if x != nil && x.IsEnterpriseUser != nil {
		return *x.IsEnterpriseUser
	}
	return false
}

func (x *GetMeResponse) GetTeamName() string {
	if x != nil && x.TeamName != nil {
		return *x.TeamName
	}
	return ""
}

func (x *GetMeResponse) GetEmailDomainType() string {
	if x != nil && x.EmailDomainType != nil {
		return *x.EmailDomainType
	}
	return ""
}

func (x *GetMeResponse) GetCountry() string {
	if x != nil && x.Country != nil {
		return *x.Country
	}
	return ""
}

func (x *GetMeResponse) GetProfilePictureUrl() string {
	if x != nil && x.ProfilePictureUrl != nil {
		return *x.ProfilePictureUrl
	}
	return ""
}

func (x *GetMeResponse) GetCursorReviewOnboardingUseCursorGithubApp() bool {
	if x != nil && x.CursorReviewOnboardingUseCursorGithubApp != nil {
		return *x.CursorReviewOnboardingUseCursorGithubApp
	}
	return false
}

func (x *GetMeResponse) GetOrganizationId() int64 {
	if x != nil && x.OrganizationId != nil {
		return *x.OrganizationId
	}
	return 0
}

func (x *GetMeResponse) GetOrganizationPublicId() string {
	if x != nil && x.OrganizationPublicId != nil {
		return *x.OrganizationPublicId
	}
	return ""
}

func (x *GetMeResponse) GetIsTeamAdmin() bool {
	if x != nil && x.IsTeamAdmin != nil {
		return *x.IsTeamAdmin
	}
	return false
}

type GetUsageLimitPolicyStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsageLimitPolicyStatusRequest) Reset() {
	*x = GetUsageLimitPolicyStatusRequest{}
	mi := &file_cursor_usage_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsageLimitPolicyStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsageLimitPolicyStatusRequest) ProtoMessage() {}

func (x *GetUsageLimitPolicyStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cursor_usage_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsageLimitPolicyStatusRequest.ProtoReflect.Descriptor instead.
func (*GetUsageLimitPolicyStatusRequest) Descriptor() ([]byte, []int) {
	return file_cursor_usage_proto_rawDescGZIP(), []int{15}
}

// Same shape as UsageLimitPolicyStatus (Cursor uses two RPCs that return
// isomorphic payloads); we ONLY consume from GetUsageLimitStatusAndActiveGrants
// but define this response for completeness.
type GetUsageLimitPolicyStatusResponse struct {
	state                         protoimpl.MessageState `protogen:"open.v1"`
	IsInSlowPool                  bool                   `protobuf:"varint,1,opt,name=is_in_slow_pool,json=isInSlowPool,proto3" json:"is_in_slow_pool,omitempty"`
	ErrorTitle                    *string                `protobuf:"bytes,2,opt,name=error_title,json=errorTitle,proto3,oneof" json:"error_title,omitempty"`
	ErrorDetail                   *string                `protobuf:"bytes,3,opt,name=error_detail,json=errorDetail,proto3,oneof" json:"error_detail,omitempty"`
	SlownessMs                    *int32                 `protobuf:"varint,4,opt,name=slowness_ms,json=slownessMs,proto3,oneof" json:"slowness_ms,omitempty"`
	Features                      map[string]string      `protobuf:"bytes,5,rep,name=features,proto3" json:"features,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CanConfigureSpendLimit        bool                   `protobuf:"varint,6,opt,name=can_configure_spend_limit,json=canConfigureSpendLimit,proto3" json:"can_configure_spend_limit,omitempty"`
	LimitType                     *string                `protobuf:"bytes,7,opt,name=limit_type,json=limitType,proto3,oneof" json:"limit_type,omitempty"`
	HasPendingRequest             bool                   `protobuf:"varint,8,opt,name=has_pending_request,json=hasPendingRequest,proto3" json:"has_pending_request,omitempty"`
	AllowedModelIds               []string               `protobuf:"bytes,9,rep,name=allowed_model_ids,json=allowedModelIds,proto3" json:"allowed_model_ids,omitempty"`
	AllowedModelTags              []string               `protobuf:"bytes,10,rep,name=allowed_model_tags,json=allowedModelTags,proto3" json:"allowed_model_tags,omitempty"`
	TrayLabel                     *string                `protobuf:"bytes,13,opt,name=tray_label,json=trayLabel,proto3,oneof" json:"tray_label,omitempty"`
	TrayDescription               *string                `protobuf:"bytes,14,opt,name=tray_description,json=trayDescription,proto3,oneof" json:"tray_description,omitempty"`
	CtaLabel                      *string                `protobuf:"bytes,15,opt,name=cta_label,json=ctaLabel,proto3,oneof" json:"cta_label,omitempty"`
	Dismissible                   *bool                  `protobuf:"varint,16,opt,name=dismissible,proto3,oneof" json:"dismissible,omitempty"`
	ResetAtMs                     *int64                 `protobuf:"varint,17,opt,name=reset_at_ms,json=resetAtMs,proto3,oneof" json:"reset_at_ms,omitempty"`
	ResetDaysRemaining            *int32                 `protobuf:"varint,18,opt,name=reset_days_remaining,json=resetDaysRemaining,proto3,oneof" json:"reset_days_remaining,omitempty"`
	CanAdjustOnDemand             *bool                  `protobuf:"varint,19,opt,name=can_adjust_on_demand,json=canAdjustOnDemand,proto3,oneof" json:"can_adjust_on_demand,omitempty"`
	RecommendedOnDemandLimitCents *int64                 `protobuf:"varint,20,opt,name=recommended_on_demand_limit_cents,json=recommendedOnDemandLimitCents,proto3,oneof" json:"recommended_on_demand_limit_cents,omitempty"`
	OnDemandMinCents              *int64                 `protobuf:"varint,21,opt,name=on_demand_min_cents,json=onDemandMinCents,proto3,oneof" json:"on_demand_min_cents,omitempty"`
	OnDemandMaxCents              *int64                 `protobuf:"varint,22,opt,name=on_demand_max_cents,json=onDemandMaxCents,proto3,oneof" json:"on_demand_max_cents,omitempty"`
	CurrentOnDemandLimitCents     *int64                 `protobuf:"varint,23,opt,name=current_on_demand_limit_cents,json=currentOnDemandLimitCents,proto3,oneof" json:"current_on_demand_limit_cents,omitempty"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *GetUsageLimitPolicyStatusResponse) Reset() {
	*x = GetUsageLimitPolicyStatusResponse{}
	mi := &file_cursor_usage_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsageLimitPolicyStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsageLimitPolicyStatusResponse) ProtoMessage() {}

func (x *GetUsageLimitPolicyStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cursor_usage_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsageLimitPolicyStatusResponse.ProtoReflect.Descriptor instead.
func (*GetUsageLimitPolicyStatusResponse) Descriptor() ([]byte, []int) {
	return file_cursor_usage_proto_rawDescGZIP(), []int{16}
}

func (x *GetUsageLimitPolicyStatusResponse) GetIsInSlowPool() bool {
	if x != nil {
		return x.IsInSlowPool
	}
	return false
}

func (x *GetUsageLimitPolicyStatusResponse) GetErrorTitle() string {
	if x != nil && x.ErrorTitle != nil {
		return *x.ErrorTitle
	}
	return ""
}

func (x *GetUsageLimitPolicyStatusResponse) GetErrorDetail() string {
	if x != nil && x.ErrorDetail != nil {
		return *x.ErrorDetail
	}
	return ""
}

func (x *GetUsageLimitPolicyStatusResponse) GetSlownessMs() int32 {
	if x != nil && x.SlownessMs != nil {
		return *x.SlownessMs
	}
	return 0
}

func (x *GetUsageLimitPolicyStatusResponse) GetFeatures() map[string]string {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *GetUsageLimitPolicyStatusResponse) GetCanConfigureSpendLimit() bool {
	if x != nil {
		return x.CanConfigureSpendLimit
	}
	return false
}

func (x *GetUsageLimitPolicyStatusResponse) GetLimitType() string {
	if x != nil && x.LimitType != nil {
		return *x.LimitType
	}
	return ""
}

func (x *GetUsageLimitPolicyStatusResponse) GetHasPendingRequest() bool {
	if x != nil {
		return x.HasPendingRequest
	}
	return false
}

func (x *GetUsageLimitPolicyStatusResponse) GetAllowedModelIds() []string {
	if x != nil {
		return x.AllowedModelIds
	}
	return nil
}

func (x *GetUsageLimitPolicyStatusResponse) GetAllowedModelTags() []string {
	if x != nil {
		return x.AllowedModelTags
	}
	return nil
}

func (x *GetUsageLimitPolicyStatusResponse) GetTrayLabel() string {
	if x != nil && x.TrayLabel != nil {
		return *x.TrayLabel
	}
	return ""
}

func (x *GetUsageLimitPolicyStatusResponse) GetTrayDescription() string {
	if x != nil && x.TrayDescription != nil {
		return *x.TrayDescription
	}
	return ""
}

func (x *GetUsageLimitPolicyStatusResponse) GetCtaLabel() string {
	if x != nil && x.CtaLabel != nil {
		return *x.CtaLabel
	}
	return ""
}

func (x *GetUsageLimitPolicyStatusResponse) GetDismissible() bool {
	if x != nil && x.Dismissible != nil {
		return *x.Dismissible
	}
	return false
}

func (x *GetUsageLimitPolicyStatusResponse) GetResetAtMs() int64 {
	if x != nil && x.ResetAtMs != nil {
		return *x.ResetAtMs
	}
	return 0
}

func (x *GetUsageLimitPolicyStatusResponse) GetResetDaysRemaining() int32 {
	if x != nil && x.ResetDaysRemaining != nil {
		return *x.ResetDaysRemaining
	}
	return 0
}

func (x *GetUsageLimitPolicyStatusResponse) GetCanAdjustOnDemand() bool {
	if x != nil && x.CanAdjustOnDemand != nil {
		return *x.CanAdjustOnDemand
	}
	return false
}

func (x *GetUsageLimitPolicyStatusResponse) GetRecommendedOnDemandLimitCents() int64 {
	if x != nil && x.RecommendedOnDemandLimitCents != nil {
		return *x.RecommendedOnDemandLimitCents
	}
	return 0
}

func (x *GetUsageLimitPolicyStatusResponse) GetOnDemandMinCents() int64 {
	if x != nil && x.OnDemandMinCents != nil {
		return *x.OnDemandMinCents
	}
	return 0
}

func (x *GetUsageLimitPolicyStatusResponse) GetOnDemandMaxCents() int64 {
	if x != nil && x.OnDemandMaxCents != nil {
		return *x.OnDemandMaxCents
	}
	return 0
}

func (x *GetUsageLimitPolicyStatusResponse) GetCurrentOnDemandLimitCents() int64 {
	if x != nil && x.CurrentOnDemandLimitCents != nil {
		return *x.CurrentOnDemandLimitCents
	}
	return 0
}

type GetCurrentPeriodUsageResponse_PlanUsage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TotalSpend       int32                  `protobuf:"varint,1,opt,name=total_spend,json=totalSpend,proto3" json:"total_spend,omitempty"`
	IncludedSpend    int32                  `protobuf:"varint,2,opt,name=included_spend,json=includedSpend,proto3" json:"included_spend,omitempty"`
	BonusSpend       int32                  `protobuf:"varint,3,opt,name=bonus_spend,json=bonusSpend,proto3" json:"bonus_spend,omitempty"`
	Remaining        int32                  `protobuf:"varint,4,opt,name=remaining,proto3" json:"remaining,omitempty"`
	Limit            int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	RemainingBonus   *bool                  `protobuf:"varint,6,opt,name=remaining_bonus,json=remainingBonus,proto3,oneof" json:"remaining_bonus,omitempty"`
	BonusTooltip     *string                `protobuf:"bytes,7,opt,name=bonus_tooltip,json=bonusTooltip,proto3,oneof" json:"bonus_tooltip,omitempty"`
	AutoSpend        *int32                 `protobuf:"varint,8,opt,name=auto_spend,json=autoSpend,proto3,oneof" json:"auto_spend,omitempty"`
	ApiSpend         *int32                 `protobuf:"varint,9,opt,name=api_spend,json=apiSpend,proto3,oneof" json:"api_spend,omitempty"`
	AutoLimit        *int32                 `protobuf:"varint,10,opt,name=auto_limit,json=autoLimit,proto3,oneof" json:"auto_limit,omitempty"`
	ApiLimit         *int32                 `protobuf:"varint,11,opt,name=api_limit,json=apiLimit,proto3,oneof" json:"api_limit,omitempty"`
	AutoPercentUsed  *float64               `protobuf:"fixed64,12,opt,name=auto_percent_used,json=autoPercentUsed,proto3,oneof" json:"auto_percent_used,omitempty"`
	ApiPercentUsed   *float64               `protobuf:"fixed64,13,opt,name=api_percent_used,json=apiPercentUsed,proto3,oneof" json:"api_percent_used,omitempty"`
	TotalPercentUsed *float64               `protobuf:"fixed64,14,opt,name=total_percent_used,json=totalPercentUsed,proto3,oneof" json:"total_percent_used,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetCurrentPeriodUsageResponse_PlanUsage) Reset() {
	*x = GetCurrentPeriodUsageResponse_PlanUsage{}
	mi := &file_cursor_usage_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentPeriodUsageResponse_PlanUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentPeriodUsageResponse_PlanUsage) ProtoMessage() {}

func (x *GetCurrentPeriodUsageResponse_PlanUsage) ProtoReflect() protoreflect.Message {
	mi := &file_cursor_usage_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentPeriodUsageResponse_PlanUsage.ProtoReflect.Descriptor instead.
func (*GetCurrentPeriodUsageResponse_PlanUsage) Descriptor() ([]byte, []int) {
	return file_cursor_usage_proto_rawDescGZIP(), []int{1, 0}
}

func (x *GetCurrentPeriodUsageResponse_PlanUsage) GetTotalSpend() int32 {
	if x != nil {
		return x.TotalSpend
	}
	return 0
}

func (x *GetCurrentPeriodUsageResponse_PlanUsage) GetIncludedSpend() int32 {
	if x != nil {
		return x.IncludedSpend
	}
	return 0
}

func (x *GetCurrentPeriodUsageResponse_PlanUsage) GetBonusSpend() int32 {
	if x != nil {
		return x.BonusSpend
	}
	return 0
}

func (x *GetCurrentPeriodUsageResponse_PlanUsage) GetRemaining() int32 {
	if x != nil {
		return x.Remaining
	}
	return 0
}

func (x *GetCurrentPeriodUsageResponse_PlanUsage) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetCurrentPeriodUsageResponse_PlanUsage) GetRemainingBonus() bool {
	if x != nil && x.RemainingBonus != nil {
		return *x.RemainingBonus
	}
	return false
}

func (x *GetCurrentPeriodUsageResponse_PlanUsage) GetBonusTooltip() string {
	if x != nil && x.BonusTooltip != nil {
		return *x.BonusTooltip
	}
	return ""
}

func (x *GetCurrentPeriodUsageResponse_PlanUsage) GetAutoSpend() int32 {
	if x != nil && x.AutoSpend != nil {
		return *x.AutoSpend
	}
	return 0
}

func (x *GetCurrentPeriodUsageResponse_PlanUsage) GetApiSpend() int32 {
	if x != nil && x.ApiSpend != nil {
		return *x.ApiSpend
	}
	return 0
}

func (x *GetCurrentPeriodUsageResponse_PlanUsage) GetAutoLimit() int32 {
	if x != nil && x.AutoLimit != nil {
		return *x.AutoLimit
	}
	return 0
}

func (x *GetCurrentPeriodUsageResponse_PlanUsage) GetApiLimit() int32 {
	if x != nil && x.ApiLimit != nil {
		return *x.ApiLimit
	}
	return 0
}

func (x *GetCurrentPeriodUsageResponse_PlanUsage) GetAutoPercentUsed() float64 {
	if x != nil && x.AutoPercentUsed != nil {
		return *x.AutoPercentUsed
	}
	return 0
}

func (x *GetCurrentPeriodUsageResponse_PlanUsage) GetApiPercentUsed() float64 {
	if x != nil && x.ApiPercentUsed != nil {
		return *x.ApiPercentUsed
	}
	return 0
}

func (x *GetCurrentPeriodUsageResponse_PlanUsage) GetTotalPercentUsed() float64 {
	if x != nil && x.TotalPercentUsed != nil {
		return *x.TotalPercentUsed
	}
	return 0
}

type GetCurrentPeriodUsageResponse_SpendLimitUsage struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	TotalSpend          int32                  `protobuf:"varint,1,opt,name=total_spend,json=totalSpend,proto3" json:"total_spend,omitempty"`
	PooledLimit         *int32                 `protobuf:"varint,2,opt,name=pooled_limit,json=pooledLimit,proto3,oneof" json:"pooled_limit,omitempty"`
	PooledUsed          *int32                 `protobuf:"varint,3,opt,name=pooled_used,json=pooledUsed,proto3,oneof" json:"pooled_used,omitempty"`
	PooledRemaining     *int32                 `protobuf:"varint,4,opt,name=pooled_remaining,json=pooledRemaining,proto3,oneof" json:"pooled_remaining,omitempty"`
	IndividualLimit     *int32                 `protobuf:"varint,5,opt,name=individual_limit,json=individualLimit,proto3,oneof" json:"individual_limit,omitempty"`
	IndividualUsed      int32                  `protobuf:"varint,6,opt,name=individual_used,json=individualUsed,proto3" json:"individual_used,omitempty"`
	IndividualRemaining int32                  `protobuf:"varint,7,opt,name=individual_remaining,json=individualRemaining,proto3" json:"individual_remaining,omitempty"`
	LimitType           string                 `protobuf:"bytes,8,opt,name=limit_type,json=limitType,proto3" json:"limit_type,omitempty"`
	OverallLimit        *int32                 `protobuf:"varint,9,opt,name=overall_limit,json=overallLimit,proto3,oneof" json:"overall_limit,omitempty"`
	OverallUsed         *int32                 `protobuf:"varint,10,opt,name=overall_used,json=overallUsed,proto3,oneof" json:"overall_used,omitempty"`
	OverallRemaining    *int32                 `protobuf:"varint,11,opt,name=overall_remaining,json=overallRemaining,proto3,oneof" json:"overall_remaining,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetCurrentPeriodUsageResponse_SpendLimitUsage) Reset() {
	*x = GetCurrentPeriodUsageResponse_SpendLimitUsage{}
	mi := &file_cursor_usage_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentPeriodUsageResponse_SpendLimitUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentPeriodUsageResponse_SpendLimitUsage) ProtoMessage() {}

func (x *GetCurrentPeriodUsageResponse_SpendLimitUsage) ProtoReflect() protoreflect.Message {
	mi := &file_cursor_usage_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentPeriodUsageResponse_SpendLimitUsage.ProtoReflect.Descriptor instead.
func (*GetCurrentPeriodUsageResponse_SpendLimitUsage) Descriptor() ([]byte, []int) {
	return file_cursor_usage_proto_rawDescGZIP(), []int{1, 1}
}

func (x *GetCurrentPeriodUsageResponse_SpendLimitUsage) GetTotalSpend() int32 {
	if x != nil {
		return x.TotalSpend
	}
	return 0
}

func (x *GetCurrentPeriodUsageResponse_SpendLimitUsage) GetPooledLimit() int32 {
	if x != nil && x.PooledLimit != nil {
		return *x.PooledLimit
	}
	return 0
}

func (x *GetCurrentPeriodUsageResponse_SpendLimitUsage) GetPooledUsed() int32 {
	if x != nil && x.PooledUsed != nil {
		return *x.PooledUsed
	}
	return 0
}

func (x *GetCurrentPeriodUsageResponse_SpendLimitUsage) GetPooledRemaining() int32 {
	if x != nil && x.PooledRemaining != nil {
		return *x.PooledRemaining
	}
	return 0
}

func (x *GetCurrentPeriodUsageResponse_SpendLimitUsage) GetIndividualLimit() int32 {
	if x != nil && x.IndividualLimit != nil {
		return *x.IndividualLimit
	}
	return 0
}

func (x *GetCurrentPeriodUsageResponse_SpendLimitUsage) GetIndividualUsed() int32 {
	if x != nil {
		return x.IndividualUsed
	}
	return 0
}

func (x *GetCurrentPeriodUsageResponse_SpendLimitUsage) GetIndividualRemaining() int32 {
	if x != nil {
		return x.IndividualRemaining
	}
	return 0
}

func (x *GetCurrentPeriodUsageResponse_SpendLimitUsage) GetLimitType() string {
	if x != nil {
		return x.LimitType
	}
	return ""
}

func (x *GetCurrentPeriodUsageResponse_SpendLimitUsage) GetOverallLimit() int32 {
	if x != nil && x.OverallLimit != nil {
		return *x.OverallLimit
	}
	return 0
}

func (x *GetCurrentPeriodUsageResponse_SpendLimitUsage) GetOverallUsed() int32 {
	if x != nil && x.OverallUsed != nil {
		return *x.OverallUsed
	}
	return 0
}

func (x *GetCurrentPeriodUsageResponse_SpendLimitUsage) GetOverallRemaining() int32 {
	if x != nil && x.OverallRemaining != nil {
		return *x.OverallRemaining
	}
	return 0
}

type GetCurrentPeriodUsageResponse_FreeBestOfNPromotion struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TrialsUsed      int32                  `protobuf:"varint,1,opt,name=trials_used,json=trialsUsed,proto3" json:"trials_used,omitempty"`
	TrialsRemaining int32                  `protobuf:"varint,2,opt,name=trials_remaining,json=trialsRemaining,proto3" json:"trials_remaining,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetCurrentPeriodUsageResponse_FreeBestOfNPromotion) Reset() {
	*x = GetCurrentPeriodUsageResponse_FreeBestOfNPromotion{}
	mi := &file_cursor_usage_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentPeriodUsageResponse_FreeBestOfNPromotion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentPeriodUsageResponse_FreeBestOfNPromotion) ProtoMessage() {}

func (x *GetCurrentPeriodUsageResponse_FreeBestOfNPromotion) ProtoReflect() protoreflect.Message {
	mi := &file_cursor_usage_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentPeriodUsageResponse_FreeBestOfNPromotion.ProtoReflect.Descriptor instead.
func (*GetCurrentPeriodUsageResponse_FreeBestOfNPromotion) Descriptor() ([]byte, []int) {
	return file_cursor_usage_proto_rawDescGZIP(), []int{1, 2}
}

func (x *GetCurrentPeriodUsageResponse_FreeBestOfNPromotion) GetTrialsUsed() int32 {
	if x != nil {
		return x.TrialsUsed
	}
	return 0
}

func (x *GetCurrentPeriodUsageResponse_FreeBestOfNPromotion) GetTrialsRemaining() int32 {
	if x != nil {
		return x.TrialsRemaining
	}
	return 0
}

type GetAggregatedUsageEventsResponse_ModelUsageAggregation struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ModelIntent      string                 `protobuf:"bytes,1,opt,name=model_intent,json=modelIntent,proto3" json:"model_intent,omitempty"`
	InputTokens      int64                  `protobuf:"varint,2,opt,name=input_tokens,json=inputTokens,proto3" json:"input_tokens,omitempty"`
	OutputTokens     int64                  `protobuf:"varint,3,opt,name=output_tokens,json=outputTokens,proto3" json:"output_tokens,omitempty"`
	CacheWriteTokens int64                  `protobuf:"varint,4,opt,name=cache_write_tokens,json=cacheWriteTokens,proto3" json:"cache_write_tokens,omitempty"`
	CacheReadTokens  int64                  `protobuf:"varint,5,opt,name=cache_read_tokens,json=cacheReadTokens,proto3" json:"cache_read_tokens,omitempty"`
	TotalCents       float64                `protobuf:"fixed64,6,opt,name=total_cents,json=totalCents,proto3" json:"total_cents,omitempty"`
	RequestCost      *float64               `protobuf:"fixed64,7,opt,name=request_cost,json=requestCost,proto3,oneof" json:"request_cost,omitempty"`
	Tier             *int32                 `protobuf:"varint,8,opt,name=tier,proto3,oneof" json:"tier,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetAggregatedUsageEventsResponse_ModelUsageAggregation) Reset() {
	*x = GetAggregatedUsageEventsResponse_ModelUsageAggregation{}
	mi := &file_cursor_usage_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAggregatedUsageEventsResponse_ModelUsageAggregation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAggregatedUsageEventsResponse_ModelUsageAggregation) ProtoMessage() {}

func (x *GetAggregatedUsageEventsResponse_ModelUsageAggregation) ProtoReflect() protoreflect.Message {
	mi := &file_cursor_usage_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAggregatedUsageEventsResponse_ModelUsageAggregation.ProtoReflect.Descriptor instead.
func (*GetAggregatedUsageEventsResponse_ModelUsageAggregation) Descriptor() ([]byte, []int) {
	return file_cursor_usage_proto_rawDescGZIP(), []int{5, 0}
}

func (x *GetAggregatedUsageEventsResponse_ModelUsageAggregation) GetModelIntent() string {
	if x != nil {
		return x.ModelIntent
	}
	return ""
}

func (x *GetAggregatedUsageEventsResponse_ModelUsageAggregation) GetInputTokens() int64 {
	if x != nil {
		return x.InputTokens
	}
	return 0
}

func (x *GetAggregatedUsageEventsResponse_ModelUsageAggregation) GetOutputTokens() int64 {
	if x != nil {
		return x.OutputTokens
	}
	return 0
}

func (x *GetAggregatedUsageEventsResponse_ModelUsageAggregation) GetCacheWriteTokens() int64 {
	if x != nil {
		return x.CacheWriteTokens
	}
	return 0
}

func (x *GetAggregatedUsageEventsResponse_ModelUsageAggregation) GetCacheReadTokens() int64 {
	if x != nil {
		return x.CacheReadTokens
	}
	return 0
}

func (x *GetAggregatedUsageEventsResponse_ModelUsageAggregation) GetTotalCents() float64 {
	if x != nil {
		return x.TotalCents
	}
	return 0
}

func (x *GetAggregatedUsageEventsResponse_ModelUsageAggregation) GetRequestCost() float64 {
	if x != nil && x.RequestCost != nil {
		return *x.RequestCost
	}
	return 0
}

func (x *GetAggregatedUsageEventsResponse_ModelUsageAggregation) GetTier() int32 {
	if x != nil && x.Tier != nil {
		return *x.Tier
	}
	return 0
}

type GetUsageLimitStatusAndActiveGrantsResponse_UsageLimitPolicyStatus struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	IsInSlowPool           bool                   `protobuf:"varint,1,opt,name=is_in_slow_pool,json=isInSlowPool,proto3" json:"is_in_slow_pool,omitempty"`
	ErrorTitle             *string                `protobuf:"bytes,2,opt,name=error_title,json=errorTitle,proto3,oneof" json:"error_title,omitempty"`
	ErrorDetail            *string                `protobuf:"bytes,3,opt,name=error_detail,json=errorDetail,proto3,oneof" json:"error_detail,omitempty"`
	SlownessMs             *int32                 `protobuf:"varint,4,opt,name=slowness_ms,json=slownessMs,proto3,oneof" json:"slowness_ms,omitempty"`
	Features               map[string]string      `protobuf:"bytes,5,rep,name=features,proto3" json:"features,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CanConfigureSpendLimit bool                   `protobuf:"varint,6,opt,name=can_configure_spend_limit,json=canConfigureSpendLimit,proto3" json:"can_configure_spend_limit,omitempty"`
	LimitType              *string                `protobuf:"bytes,7,opt,name=limit_type,json=limitType,proto3,oneof" json:"limit_type,omitempty"`
	HasPendingRequest      bool                   `protobuf:"varint,8,opt,name=has_pending_request,json=hasPendingRequest,proto3" json:"has_pending_request,omitempty"`
	AllowedModelIds        []string               `protobuf:"bytes,9,rep,name=allowed_model_ids,json=allowedModelIds,proto3" json:"allowed_model_ids,omitempty"`
	AllowedModelTags       []string               `protobuf:"bytes,10,rep,name=allowed_model_tags,json=allowedModelTags,proto3" json:"allowed_model_tags,omitempty"`
	// primary_button omitted (ErrorButton has complex oneof; not needed here)
	// stage (LimitHitStage enum) omitted; wire compatibility preserved
	TrayLabel                     *string `protobuf:"bytes,13,opt,name=tray_label,json=trayLabel,proto3,oneof" json:"tray_label,omitempty"`
	TrayDescription               *string `protobuf:"bytes,14,opt,name=tray_description,json=trayDescription,proto3,oneof" json:"tray_description,omitempty"`
	CtaLabel                      *string `protobuf:"bytes,15,opt,name=cta_label,json=ctaLabel,proto3,oneof" json:"cta_label,omitempty"`
	Dismissible                   *bool   `protobuf:"varint,16,opt,name=dismissible,proto3,oneof" json:"dismissible,omitempty"`
	ResetAtMs                     *int64  `protobuf:"varint,17,opt,name=reset_at_ms,json=resetAtMs,proto3,oneof" json:"reset_at_ms,omitempty"`
	ResetDaysRemaining            *int32  `protobuf:"varint,18,opt,name=reset_days_remaining,json=resetDaysRemaining,proto3,oneof" json:"reset_days_remaining,omitempty"`
	CanAdjustOnDemand             *bool   `protobuf:"varint,19,opt,name=can_adjust_on_demand,json=canAdjustOnDemand,proto3,oneof" json:"can_adjust_on_demand,omitempty"`
	RecommendedOnDemandLimitCents *int64  `protobuf:"varint,20,opt,name=recommended_on_demand_limit_cents,json=recommendedOnDemandLimitCents,proto3,oneof" json:"recommended_on_demand_limit_cents,omitempty"`
	OnDemandMinCents              *int64  `protobuf:"varint,21,opt,name=on_demand_min_cents,json=onDemandMinCents,proto3,oneof" json:"on_demand_min_cents,omitempty"`
	OnDemandMaxCents              *int64  `protobuf:"varint,22,opt,name=on_demand_max_cents,json=onDemandMaxCents,proto3,oneof" json:"on_demand_max_cents,omitempty"`
	CurrentOnDemandLimitCents     *int64  `protobuf:"varint,23,opt,name=current_on_demand_limit_cents,json=currentOnDemandLimitCents,proto3,oneof" json:"current_on_demand_limit_cents,omitempty"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *GetUsageLimitStatusAndActiveGrantsResponse_UsageLimitPolicyStatus) Reset() {
	*x = GetUsageLimitStatusAndActiveGrantsResponse_UsageLimitPolicyStatus{}
	mi := &file_cursor_usage_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsageLimitStatusAndActiveGrantsResponse_UsageLimitPolicyStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsageLimitStatusAndActiveGrantsResponse_UsageLimitPolicyStatus) ProtoMessage() {}

func (x *GetUsageLimitStatusAndActiveGrantsResponse_UsageLimitPolicyStatus) ProtoReflect() protoreflect.Message {
	mi := &file_cursor_usage_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsageLimitStatusAndActiveGrantsResponse_UsageLimitPolicyStatus.ProtoReflect.Descriptor instead.
func (*GetUsageLimitStatusAndActiveGrantsResponse_UsageLimitPolicyStatus) Descriptor() ([]byte, []int) {
	return file_cursor_usage_proto_rawDescGZIP(), []int{12, 0}
}

func (x *GetUsageLimitStatusAndActiveGrantsResponse_UsageLimitPolicyStatus) GetIsInSlowPool() bool {
	if x != nil {
		return x.IsInSlowPool
	}
	return false
}

func (x *GetUsageLimitStatusAndActiveGrantsResponse_UsageLimitPolicyStatus) GetErrorTitle() string {
	if x != nil && x.ErrorTitle != nil {
		return *x.ErrorTitle
	}
	return ""
}

func (x *GetUsageLimitStatusAndActiveGrantsResponse_UsageLimitPolicyStatus) GetErrorDetail() string {
	if x != nil && x.ErrorDetail != nil {
		return *x.ErrorDetail
	}
	return ""
}

func (x *GetUsageLimitStatusAndActiveGrantsResponse_UsageLimitPolicyStatus) GetSlownessMs() int32 {
	if x != nil && x.SlownessMs != nil {
		return *x.SlownessMs
	}
	return 0
}

func (x *GetUsageLimitStatusAndActiveGrantsResponse_UsageLimitPolicyStatus) GetFeatures() map[string]string {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *GetUsageLimitStatusAndActiveGrantsResponse_UsageLimitPolicyStatus) GetCanConfigureSpendLimit() bool {
	if x != nil {
		return x.CanConfigureSpendLimit
	}
	return false
}

func (x *GetUsageLimitStatusAndActiveGrantsResponse_UsageLimitPolicyStatus) GetLimitType() string {
	if x != nil && x.LimitType != nil {
		return *x.LimitType
	}
	return ""
}

func (x *GetUsageLimitStatusAndActiveGrantsResponse_UsageLimitPolicyStatus) GetHasPendingRequest() bool {
	if x != nil {
		return x.HasPendingRequest
	}
	return false
}

func (x *GetUsageLimitStatusAndActiveGrantsResponse_UsageLimitPolicyStatus) GetAllowedModelIds() []string {
	if x != nil {
		return x.AllowedModelIds
	}
	return nil
}

func (x *GetUsageLimitStatusAndActiveGrantsResponse_UsageLimitPolicyStatus) GetAllowedModelTags() []string {
	if x != nil {
		return x.AllowedModelTags
	}
	return nil
}

func (x *GetUsageLimitStatusAndActiveGrantsResponse_UsageLimitPolicyStatus) GetTrayLabel() string {
	if x != nil && x.TrayLabel != nil {
		return *x.TrayLabel
	}
	return ""
}

func (x *GetUsageLimitStatusAndActiveGrantsResponse_UsageLimitPolicyStatus) GetTrayDescription() string {
	if x != nil && x.TrayDescription != nil {
		return *x.TrayDescription
	}
	return ""
}

func (x *GetUsageLimitStatusAndActiveGrantsResponse_UsageLimitPolicyStatus) GetCtaLabel() string {
	if x != nil && x.CtaLabel != nil {
		return *x.CtaLabel
	}
	return ""
}

func (x *GetUsageLimitStatusAndActiveGrantsResponse_UsageLimitPolicyStatus) GetDismissible() bool {
	if x != nil && x.Dismissible != nil {
		return *x.Dismissible
	}
	return false
}

func (x *GetUsageLimitStatusAndActiveGrantsResponse_UsageLimitPolicyStatus) GetResetAtMs() int64 {
	if x != nil && x.ResetAtMs != nil {
		return *x.ResetAtMs
	}
	return 0
}

func (x *GetUsageLimitStatusAndActiveGrantsResponse_UsageLimitPolicyStatus) GetResetDaysRemaining() int32 {
	if x != nil && x.ResetDaysRemaining != nil {
		return *x.ResetDaysRemaining
	}
	return 0
}

func (x *GetUsageLimitStatusAndActiveGrantsResponse_UsageLimitPolicyStatus) GetCanAdjustOnDemand() bool {
	if x != nil && x.CanAdjustOnDemand != nil {
		return *x.CanAdjustOnDemand
	}
	return false
}

func (x *GetUsageLimitStatusAndActiveGrantsResponse_UsageLimitPolicyStatus) GetRecommendedOnDemandLimitCents() int64 {
	if x != nil && x.RecommendedOnDemandLimitCents != nil {
		return *x.RecommendedOnDemandLimitCents
	}
	return 0
}

func (x *GetUsageLimitStatusAndActiveGrantsResponse_UsageLimitPolicyStatus) GetOnDemandMinCents() int64 {
	if x != nil && x.OnDemandMinCents != nil {
		return *x.OnDemandMinCents
	}
	return 0
}

func (x *GetUsageLimitStatusAndActiveGrantsResponse_UsageLimitPolicyStatus) GetOnDemandMaxCents() int64 {
	if x != nil && x.OnDemandMaxCents != nil {
		return *x.OnDemandMaxCents
	}
	return 0
}

func (x *GetUsageLimitStatusAndActiveGrantsResponse_UsageLimitPolicyStatus) GetCurrentOnDemandLimitCents() int64 {
	if x != nil && x.CurrentOnDemandLimitCents != nil {
		return *x.CurrentOnDemandLimitCents
	}
	return 0
}

var File_cursor_usage_proto protoreflect.FileDescriptor

const file_cursor_usage_proto_rawDesc = "" +
	"\n" +
	"\x12cursor_usage.proto\x12\fcursor_usage\"H\n" +
	"\x1cGetCurrentPeriodUsageRequest\x12\x1c\n" +
	"\ateam_id\x18\x01 \x01(\x05H\x00R\x06teamId\x88\x01\x01B\n" +
	"\n" +
	"\b_team_id\"\x96\x12\n" +
	"\x1dGetCurrentPeriodUsageResponse\x12.\n" +
	"\x13billing_cycle_start\x18\x01 \x01(\x03R\x11billingCycleStart\x12*\n" +
	"\x11billing_cycle_end\x18\x02 \x01(\x03R\x0fbillingCycleEnd\x12T\n" +
	"\n" +
	"plan_usage\x18\x03 \x01(\v25.cursor_usage.GetCurrentPeriodUsageResponse.PlanUsageR\tplanUsage\x12g\n" +
	"\x11spend_limit_usage\x18\x04 \x01(\v2;.cursor_usage.GetCurrentPeriodUsageResponse.SpendLimitUsageR\x0fspendLimitUsage\x120\n" +
	"\x11display_threshold\x18\x05 \x01(\x05H\x00R\x10displayThreshold\x88\x01\x01\x12\x18\n" +
	"\aenabled\x18\x06 \x01(\bR\aenabled\x12'\n" +
	"\x0fdisplay_message\x18\a \x01(\tR\x0edisplayMessage\x12}\n" +
	"\x18free_best_of_n_promotion\x18\b \x01(\v2@.cursor_usage.GetCurrentPeriodUsageResponse.FreeBestOfNPromotionH\x01R\x14freeBestOfNPromotion\x88\x01\x01\x12Q\n" +
	"#auto_model_selected_display_message\x18\v \x01(\tH\x02R\x1fautoModelSelectedDisplayMessage\x88\x01\x01\x12S\n" +
	"$named_model_selected_display_message\x18\f \x01(\tH\x03R namedModelSelectedDisplayMessage\x88\x01\x01\x12,\n" +
	"\x12auto_bucket_models\x18\r \x03(\tR\x10autoBucketModels\x1a\xc1\x05\n" +
	"\tPlanUsage\x12\x1f\n" +
	"\vtotal_spend\x18\x01 \x01(\x05R\n" +
	"totalSpend\x12%\n" +
	"\x0eincluded_spend\x18\x02 \x01(\x05R\rincludedSpend\x12\x1f\n" +
	"\vbonus_spend\x18\x03 \x01(\x05R\n" +
	"bonusSpend\x12\x1c\n" +
	"\tremaining\x18\x04 \x01(\x05R\tremaining\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\x12,\n" +
	"\x0fremaining_bonus\x18\x06 \x01(\bH\x00R\x0eremainingBonus\x88\x01\x01\x12(\n" +
	"\rbonus_tooltip\x18\a \x01(\tH\x01R\fbonusTooltip\x88\x01\x01\x12\"\n" +
	"\n" +
	"auto_spend\x18\b \x01(\x05H\x02R\tautoSpend\x88\x01\x01\x12 \n" +
	"\tapi_spend\x18\t \x01(\x05H\x03R\bapiSpend\x88\x01\x01\x12\"\n" +
	"\n" +
	"auto_limit\x18\n" +
	" \x01(\x05H\x04R\tautoLimit\x88\x01\x01\x12 \n" +
	"\tapi_limit\x18\v \x01(\x05H\x05R\bapiLimit\x88\x01\x01\x12/\n" +
	"\x11auto_percent_used\x18\f \x01(\x01H\x06R\x0fautoPercentUsed\x88\x01\x01\x12-\n" +
	"\x10api_percent_used\x18\r \x01(\x01H\aR\x0eapiPercentUsed\x88\x01\x01\x121\n" +
	"\x12total_percent_used\x18\x0e \x01(\x01H\bR\x10totalPercentUsed\x88\x01\x01B\x12\n" +
	"\x10_remaining_bonusB\x10\n" +
	"\x0e_bonus_tooltipB\r\n" +
	"\v_auto_spendB\f\n" +
	"\n" +
	"_api_spendB\r\n" +
	"\v_auto_limitB\f\n" +
	"\n" +
	"_api_limitB\x14\n" +
	"\x12_auto_percent_usedB\x13\n" +
	"\x11_api_percent_usedB\x15\n" +
	"\x13_total_percent_used\x1a\xe3\x04\n" +
	"\x0fSpendLimitUsage\x12\x1f\n" +
	"\vtotal_spend\x18\x01 \x01(\x05R\n" +
	"totalSpend\x12&\n" +
	"\fpooled_limit\x18\x02 \x01(\x05H\x00R\vpooledLimit\x88\x01\x01\x12$\n" +
	"\vpooled_used\x18\x03 \x01(\x05H\x01R\n" +
	"pooledUsed\x88\x01\x01\x12.\n" +
	"\x10pooled_remaining\x18\x04 \x01(\x05H\x02R\x0fpooledRemaining\x88\x01\x01\x12.\n" +
	"\x10individual_limit\x18\x05 \x01(\x05H\x03R\x0findividualLimit\x88\x01\x01\x12'\n" +
	"\x0findividual_used\x18\x06 \x01(\x05R\x0eindividualUsed\x121\n" +
	"\x14individual_remaining\x18\a \x01(\x05R\x13individualRemaining\x12\x1d\n" +
	"\n" +
	"limit_type\x18\b \x01(\tR\tlimitType\x12(\n" +
	"\roverall_limit\x18\t \x01(\x05H\x04R\foverallLimit\x88\x01\x01\x12&\n" +
	"\foverall_used\x18\n" +
	" \x01(\x05H\x05R\voverallUsed\x88\x01\x01\x120\n" +
	"\x11overall_remaining\x18\v \x01(\x05H\x06R\x10overallRemaining\x88\x01\x01B\x0f\n" +
	"\r_pooled_limitB\x0e\n" +
	"\f_pooled_usedB\x13\n" +
	"\x11_pooled_remainingB\x13\n" +
	"\x11_individual_limitB\x10\n" +
	"\x0e_overall_limitB\x0f\n" +
	"\r_overall_usedB\x14\n" +
	"\x12_overall_remaining\x1ab\n" +
	"\x14FreeBestOfNPromotion\x12\x1f\n" +
	"\vtrials_used\x18\x01 \x01(\x05R\n" +
	"trialsUsed\x12)\n" +
	"\x10trials_remaining\x18\x02 \x01(\x05R\x0ftrialsRemainingB\x14\n" +
	"\x12_display_thresholdB\x1b\n" +
	"\x19_free_best_of_n_promotionB&\n" +
	"$_auto_model_selected_display_messageB'\n" +
	"%_named_model_selected_display_message\"I\n" +
	"\x1dGetCurrentBillingCycleRequest\x12\x1c\n" +
	"\ateam_id\x18\x01 \x01(\x05H\x00R\x06teamId\x88\x01\x01B\n" +
	"\n" +
	"\b_team_id\"\x8a\x01\n" +
	"\x1eGetCurrentBillingCycleResponse\x125\n" +
	"\x17start_date_epoch_millis\x18\x01 \x01(\x03R\x14startDateEpochMillis\x121\n" +
	"\x15end_date_epoch_millis\x18\x02 \x01(\x03R\x12endDateEpochMillis\"\xc4\x01\n" +
	"\x1fGetAggregatedUsageEventsRequest\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\x05R\x06teamId\x12\"\n" +
	"\n" +
	"start_date\x18\x02 \x01(\x03H\x00R\tstartDate\x88\x01\x01\x12\x1e\n" +
	"\bend_date\x18\x03 \x01(\x03H\x01R\aendDate\x88\x01\x01\x12\x1c\n" +
	"\auser_id\x18\x04 \x01(\x05H\x02R\x06userId\x88\x01\x01B\r\n" +
	"\v_start_dateB\v\n" +
	"\t_end_dateB\n" +
	"\n" +
	"\b_user_id\"\xdc\x06\n" +
	" GetAggregatedUsageEventsResponse\x12h\n" +
	"\faggregations\x18\x01 \x03(\v2D.cursor_usage.GetAggregatedUsageEventsResponse.ModelUsageAggregationR\faggregations\x12,\n" +
	"\x12total_input_tokens\x18\x02 \x01(\x03R\x10totalInputTokens\x12.\n" +
	"\x13total_output_tokens\x18\x03 \x01(\x03R\x11totalOutputTokens\x127\n" +
	"\x18total_cache_write_tokens\x18\x04 \x01(\x03R\x15totalCacheWriteTokens\x125\n" +
	"\x17total_cache_read_tokens\x18\x05 \x01(\x03R\x14totalCacheReadTokens\x12(\n" +
	"\x10total_cost_cents\x18\x06 \x01(\x01R\x0etotalCostCents\x121\n" +
	"\x15percent_of_burst_used\x18\a \x01(\x01R\x12percentOfBurstUsed\x121\n" +
	"\x12total_request_cost\x18\b \x01(\x01H\x00R\x10totalRequestCost\x88\x01\x01\x1a\xd8\x02\n" +
	"\x15ModelUsageAggregation\x12!\n" +
	"\fmodel_intent\x18\x01 \x01(\tR\vmodelIntent\x12!\n" +
	"\finput_tokens\x18\x02 \x01(\x03R\vinputTokens\x12#\n" +
	"\routput_tokens\x18\x03 \x01(\x03R\foutputTokens\x12,\n" +
	"\x12cache_write_tokens\x18\x04 \x01(\x03R\x10cacheWriteTokens\x12*\n" +
	"\x11cache_read_tokens\x18\x05 \x01(\x03R\x0fcacheReadTokens\x12\x1f\n" +
	"\vtotal_cents\x18\x06 \x01(\x01R\n" +
	"totalCents\x12&\n" +
	"\frequest_cost\x18\a \x01(\x01H\x00R\vrequestCost\x88\x01\x01\x12\x17\n" +
	"\x04tier\x18\b \x01(\x05H\x01R\x04tier\x88\x01\x01B\x0f\n" +
	"\r_request_costB\a\n" +
	"\x05_tierB\x15\n" +
	"\x13_total_request_cost\">\n" +
	"#GetUsageBasedPremiumRequestsRequest\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\x05R\x06teamId\"g\n" +
	"$GetUsageBasedPremiumRequestsResponse\x12?\n" +
	"\x1cusage_based_premium_requests\x18\x01 \x01(\bR\x19usageBasedPremiumRequests\"?\n" +
	"\x13GetHardLimitRequest\x12\x1c\n" +
	"\ateam_id\x18\x01 \x01(\x05H\x00R\x06teamId\x88\x01\x01B\n" +
	"\n" +
	"\b_team_id\"\x86\x05\n" +
	"\x14GetHardLimitResponse\x12\x1d\n" +
	"\n" +
	"hard_limit\x18\x01 \x01(\x05R\thardLimit\x123\n" +
	"\x16no_usage_based_allowed\x18\x02 \x01(\bR\x13noUsageBasedAllowed\x122\n" +
	"\x13hard_limit_per_user\x18\x03 \x01(\x05H\x00R\x10hardLimitPerUser\x88\x01\x01\x12B\n" +
	"\x1eper_user_monthly_limit_dollars\x18\x04 \x01(\x05R\x1aperUserMonthlyLimitDollars\x121\n" +
	"\x15is_dynamic_team_limit\x18\x05 \x01(\bR\x12isDynamicTeamLimit\x12W\n" +
	")has_pending_setup_onboarding_credit_claim\x18\x06 \x01(\bR$hasPendingSetupOnboardingCreditClaim\x121\n" +
	"\x15is_setup_promo_active\x18\a \x01(\bR\x12isSetupPromoActive\x12<\n" +
	"\x18setup_promo_amount_cents\x18\b \x01(\x05H\x01R\x15setupPromoAmountCents\x88\x01\x01\x12K\n" +
	" setup_promo_credit_validity_days\x18\t \x01(\x05H\x02R\x1csetupPromoCreditValidityDays\x88\x01\x01B\x16\n" +
	"\x14_hard_limit_per_userB\x1b\n" +
	"\x19_setup_promo_amount_centsB#\n" +
	"!_setup_promo_credit_validity_days\"\x87\x04\n" +
	"\x11ActiveCreditGrant\x12\x19\n" +
	"\bgrant_id\x18\x01 \x01(\tR\agrantId\x12\x1f\n" +
	"\vtotal_cents\x18\x02 \x01(\x03R\n" +
	"totalCents\x12'\n" +
	"\x0fremaining_cents\x18\x03 \x01(\x03R\x0eremainingCents\x12\"\n" +
	"\rexpires_at_ms\x18\x04 \x01(\x03R\vexpiresAtMs\x12*\n" +
	"\x11allowed_model_ids\x18\x05 \x03(\tR\x0fallowedModelIds\x12,\n" +
	"\x12allowed_model_tags\x18\x06 \x03(\tR\x10allowedModelTags\x12\x1d\n" +
	"\n" +
	"grant_type\x18\a \x01(\tR\tgrantType\x12$\n" +
	"\vslowness_ms\x18\b \x01(\x05H\x00R\n" +
	"slownessMs\x88\x01\x01\x12\x1b\n" +
	"\x06source\x18\t \x01(\tH\x01R\x06source\x88\x01\x01\x12(\n" +
	"\rcampaign_name\x18\n" +
	" \x01(\tH\x02R\fcampaignName\x88\x01\x01\x12$\n" +
	"\x0eshow_in_client\x18\v \x01(\bR\fshowInClient\x120\n" +
	"\x14allowed_client_types\x18\f \x03(\tR\x12allowedClientTypesB\x0e\n" +
	"\f_slowness_msB\t\n" +
	"\a_sourceB\x10\n" +
	"\x0e_campaign_name\"+\n" +
	")GetUsageLimitStatusAndActiveGrantsRequest\"\xbf\r\n" +
	"*GetUsageLimitStatusAndActiveGrantsResponse\x12\x8a\x01\n" +
	"\x19usage_limit_policy_status\x18\x01 \x01(\v2O.cursor_usage.GetUsageLimitStatusAndActiveGrantsResponse.UsageLimitPolicyStatusR\x16usageLimitPolicyStatus\x12D\n" +
	"\ractive_grants\x18\x02 \x03(\v2\x1f.cursor_usage.ActiveCreditGrantR\factiveGrants\x1a\xbd\v\n" +
	"\x16UsageLimitPolicyStatus\x12%\n" +
	"\x0fis_in_slow_pool\x18\x01 \x01(\bR\fisInSlowPool\x12$\n" +
	"\verror_title\x18\x02 \x01(\tH\x00R\n" +
	"errorTitle\x88\x01\x01\x12&\n" +
	"\ferror_detail\x18\x03 \x01(\tH\x01R\verrorDetail\x88\x01\x01\x12$\n" +
	"\vslowness_ms\x18\x04 \x01(\x05H\x02R\n" +
	"slownessMs\x88\x01\x01\x12y\n" +
	"\bfeatures\x18\x05 \x03(\v2].cursor_usage.GetUsageLimitStatusAndActiveGrantsResponse.UsageLimitPolicyStatus.FeaturesEntryR\bfeatures\x129\n" +
	"\x19can_configure_spend_limit\x18\x06 \x01(\bR\x16canConfigureSpendLimit\x12\"\n" +
	"\n" +
	"limit_type\x18\a \x01(\tH\x03R\tlimitType\x88\x01\x01\x12.\n" +
	"\x13has_pending_request\x18\b \x01(\bR\x11hasPendingRequest\x12*\n" +
	"\x11allowed_model_ids\x18\t \x03(\tR\x0fallowedModelIds\x12,\n" +
	"\x12allowed_model_tags\x18\n" +
	" \x03(\tR\x10allowedModelTags\x12\"\n" +
	"\n" +
	"tray_label\x18\r \x01(\tH\x04R\ttrayLabel\x88\x01\x01\x12.\n" +
	"\x10tray_description\x18\x0e \x01(\tH\x05R\x0ftrayDescription\x88\x01\x01\x12 \n" +
	"\tcta_label\x18\x0f \x01(\tH\x06R\bctaLabel\x88\x01\x01\x12%\n" +
	"\vdismissible\x18\x10 \x01(\bH\aR\vdismissible\x88\x01\x01\x12#\n" +
	"\vreset_at_ms\x18\x11 \x01(\x03H\bR\tresetAtMs\x88\x01\x01\x125\n" +
	"\x14reset_days_remaining\x18\x12 \x01(\x05H\tR\x12resetDaysRemaining\x88\x01\x01\x124\n" +
	"\x14can_adjust_on_demand\x18\x13 \x01(\bH\n" +
	"R\x11canAdjustOnDemand\x88\x01\x01\x12M\n" +
	"!recommended_on_demand_limit_cents\x18\x14 \x01(\x03H\vR\x1drecommendedOnDemandLimitCents\x88\x01\x01\x122\n" +
	"\x13on_demand_min_cents\x18\x15 \x01(\x03H\fR\x10onDemandMinCents\x88\x01\x01\x122\n" +
	"\x13on_demand_max_cents\x18\x16 \x01(\x03H\rR\x10onDemandMaxCents\x88\x01\x01\x12E\n" +
	"\x1dcurrent_on_demand_limit_cents\x18\x17 \x01(\x03H\x0eR\x19currentOnDemandLimitCents\x88\x01\x01\x1a;\n" +
	"\rFeaturesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x0e\n" +
	"\f_error_titleB\x0f\n" +
	"\r_error_detailB\x0e\n" +
	"\f_slowness_msB\r\n" +
	"\v_limit_typeB\r\n" +
	"\v_tray_labelB\x13\n" +
	"\x11_tray_descriptionB\f\n" +
	"\n" +
	"_cta_labelB\x0e\n" +
	"\f_dismissibleB\x0e\n" +
	"\f_reset_at_msB\x17\n" +
	"\x15_reset_days_remainingB\x17\n" +
	"\x15_can_adjust_on_demandB$\n" +
	"\"_recommended_on_demand_limit_centsB\x16\n" +
	"\x14_on_demand_min_centsB\x16\n" +
	"\x14_on_demand_max_centsB \n" +
	"\x1e_current_on_demand_limit_cents\"\x88\x01\n" +
	"\fGetMeRequest\x12\x1c\n" +
	"\ateam_id\x18\x01 \x01(\x05H\x00R\x06teamId\x88\x01\x01\x125\n" +
	"\x14source_site_hostname\x18\x02 \x01(\tH\x01R\x12sourceSiteHostname\x88\x01\x01B\n" +
	"\n" +
	"\b_team_idB\x17\n" +
	"\x15_source_site_hostname\"\xfc\a\n" +
	"\rGetMeResponse\x12\x17\n" +
	"\aauth_id\x18\x01 \x01(\tR\x06authId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\x12\x19\n" +
	"\x05email\x18\x03 \x01(\tH\x00R\x05email\x88\x01\x01\x12\"\n" +
	"\n" +
	"first_name\x18\x04 \x01(\tH\x01R\tfirstName\x88\x01\x01\x12 \n" +
	"\tlast_name\x18\x05 \x01(\tH\x02R\blastName\x88\x01\x01\x12 \n" +
	"\tworkos_id\x18\x06 \x01(\tH\x03R\bworkosId\x88\x01\x01\x12\x1c\n" +
	"\ateam_id\x18\a \x01(\x05H\x04R\x06teamId\x88\x01\x01\x12\"\n" +
	"\n" +
	"created_at\x18\b \x01(\tH\x05R\tcreatedAt\x88\x01\x01\x121\n" +
	"\x12is_enterprise_user\x18\t \x01(\bH\x06R\x10isEnterpriseUser\x88\x01\x01\x12 \n" +
	"\tteam_name\x18\n" +
	" \x01(\tH\aR\bteamName\x88\x01\x01\x12/\n" +
	"\x11email_domain_type\x18\v \x01(\tH\bR\x0femailDomainType\x88\x01\x01\x12\x1d\n" +
	"\acountry\x18\f \x01(\tH\tR\acountry\x88\x01\x01\x123\n" +
	"\x13profile_picture_url\x18\r \x01(\tH\n" +
	"R\x11profilePictureUrl\x88\x01\x01\x12e\n" +
	".cursor_review_onboarding_use_cursor_github_app\x18\x0e \x01(\bH\vR(cursorReviewOnboardingUseCursorGithubApp\x88\x01\x01\x12,\n" +
	"\x0forganization_id\x18\x0f \x01(\x03H\fR\x0eorganizationId\x88\x01\x01\x129\n" +
	"\x16organization_public_id\x18\x10 \x01(\tH\rR\x14organizationPublicId\x88\x01\x01\x12'\n" +
	"\ris_team_admin\x18\x11 \x01(\bH\x0eR\visTeamAdmin\x88\x01\x01B\b\n" +
	"\x06_emailB\r\n" +
	"\v_first_nameB\f\n" +
	"\n" +
	"_last_nameB\f\n" +
	"\n" +
	"_workos_idB\n" +
	"\n" +
	"\b_team_idB\r\n" +
	"\v_created_atB\x15\n" +
	"\x13_is_enterprise_userB\f\n" +
	"\n" +
	"_team_nameB\x14\n" +
	"\x12_email_domain_typeB\n" +
	"\n" +
	"\b_countryB\x16\n" +
	"\x14_profile_picture_urlB1\n" +
	"/_cursor_review_onboarding_use_cursor_github_appB\x12\n" +
	"\x10_organization_idB\x19\n" +
	"\x17_organization_public_idB\x10\n" +
	"\x0e_is_team_admin\"\"\n" +
	" GetUsageLimitPolicyStatusRequest\"\xa8\v\n" +
	"!GetUsageLimitPolicyStatusResponse\x12%\n" +
	"\x0fis_in_slow_pool\x18\x01 \x01(\bR\fisInSlowPool\x12$\n" +
	"\verror_title\x18\x02 \x01(\tH\x00R\n" +
	"errorTitle\x88\x01\x01\x12&\n" +
	"\ferror_detail\x18\x03 \x01(\tH\x01R\verrorDetail\x88\x01\x01\x12$\n" +
	"\vslowness_ms\x18\x04 \x01(\x05H\x02R\n" +
	"slownessMs\x88\x01\x01\x12Y\n" +
	"\bfeatures\x18\x05 \x03(\v2=.cursor_usage.GetUsageLimitPolicyStatusResponse.FeaturesEntryR\bfeatures\x129\n" +
	"\x19can_configure_spend_limit\x18\x06 \x01(\bR\x16canConfigureSpendLimit\x12\"\n" +
	"\n" +
	"limit_type\x18\a \x01(\tH\x03R\tlimitType\x88\x01\x01\x12.\n" +
	"\x13has_pending_request\x18\b \x01(\bR\x11hasPendingRequest\x12*\n" +
	"\x11allowed_model_ids\x18\t \x03(\tR\x0fallowedModelIds\x12,\n" +
	"\x12allowed_model_tags\x18\n" +
	" \x03(\tR\x10allowedModelTags\x12\"\n" +
	"\n" +
	"tray_label\x18\r \x01(\tH\x04R\ttrayLabel\x88\x01\x01\x12.\n" +
	"\x10tray_description\x18\x0e \x01(\tH\x05R\x0ftrayDescription\x88\x01\x01\x12 \n" +
	"\tcta_label\x18\x0f \x01(\tH\x06R\bctaLabel\x88\x01\x01\x12%\n" +
	"\vdismissible\x18\x10 \x01(\bH\aR\vdismissible\x88\x01\x01\x12#\n" +
	"\vreset_at_ms\x18\x11 \x01(\x03H\bR\tresetAtMs\x88\x01\x01\x125\n" +
	"\x14reset_days_remaining\x18\x12 \x01(\x05H\tR\x12resetDaysRemaining\x88\x01\x01\x124\n" +
	"\x14can_adjust_on_demand\x18\x13 \x01(\bH\n" +
	"R\x11canAdjustOnDemand\x88\x01\x01\x12M\n" +
	"!recommended_on_demand_limit_cents\x18\x14 \x01(\x03H\vR\x1drecommendedOnDemandLimitCents\x88\x01\x01\x122\n" +
	"\x13on_demand_min_cents\x18\x15 \x01(\x03H\fR\x10onDemandMinCents\x88\x01\x01\x122\n" +
	"\x13on_demand_max_cents\x18\x16 \x01(\x03H\rR\x10onDemandMaxCents\x88\x01\x01\x12E\n" +
	"\x1dcurrent_on_demand_limit_cents\x18\x17 \x01(\x03H\x0eR\x19currentOnDemandLimitCents\x88\x01\x01\x1a;\n" +
	"\rFeaturesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x0e\n" +
	"\f_error_titleB\x0f\n" +
	"\r_error_detailB\x0e\n" +
	"\f_slowness_msB\r\n" +
	"\v_limit_typeB\r\n" +
	"\v_tray_labelB\x13\n" +
	"\x11_tray_descriptionB\f\n" +
	"\n" +
	"_cta_labelB\x0e\n" +
	"\f_dismissibleB\x0e\n" +
	"\f_reset_at_msB\x17\n" +
	"\x15_reset_days_remainingB\x17\n" +
	"\x15_can_adjust_on_demandB$\n" +
	"\"_recommended_on_demand_limit_centsB\x16\n" +
	"\x14_on_demand_min_centsB\x16\n" +
	"\x14_on_demand_max_centsB \n" +
	"\x1e_current_on_demand_limit_centsB8Z6github.com/router-for-me/cursor-proto/usage/pb;usagepbb\x06proto3"

var (
	file_cursor_usage_proto_rawDescOnce sync.Once
	file_cursor_usage_proto_rawDescData []byte
)

func file_cursor_usage_proto_rawDescGZIP() []byte {
	file_cursor_usage_proto_rawDescOnce.Do(func() {
		file_cursor_usage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cursor_usage_proto_rawDesc), len(file_cursor_usage_proto_rawDesc)))
	})
	return file_cursor_usage_proto_rawDescData
}

var file_cursor_usage_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_cursor_usage_proto_goTypes = []any{
	(*GetCurrentPeriodUsageRequest)(nil),                                      // 0: cursor_usage.GetCurrentPeriodUsageRequest
	(*GetCurrentPeriodUsageResponse)(nil),                                     // 1: cursor_usage.GetCurrentPeriodUsageResponse
	(*GetCurrentBillingCycleRequest)(nil),                                     // 2: cursor_usage.GetCurrentBillingCycleRequest
	(*GetCurrentBillingCycleResponse)(nil),                                    // 3: cursor_usage.GetCurrentBillingCycleResponse
	(*GetAggregatedUsageEventsRequest)(nil),                                   // 4: cursor_usage.GetAggregatedUsageEventsRequest
	(*GetAggregatedUsageEventsResponse)(nil),                                  // 5: cursor_usage.GetAggregatedUsageEventsResponse
	(*GetUsageBasedPremiumRequestsRequest)(nil),                               // 6: cursor_usage.GetUsageBasedPremiumRequestsRequest
	(*GetUsageBasedPremiumRequestsResponse)(nil),                              // 7: cursor_usage.GetUsageBasedPremiumRequestsResponse
	(*GetHardLimitRequest)(nil),                                               // 8: cursor_usage.GetHardLimitRequest
	(*GetHardLimitResponse)(nil),                                              // 9: cursor_usage.GetHardLimitResponse
	(*ActiveCreditGrant)(nil),                                                 // 10: cursor_usage.ActiveCreditGrant
	(*GetUsageLimitStatusAndActiveGrantsRequest)(nil),                         // 11: cursor_usage.GetUsageLimitStatusAndActiveGrantsRequest
	(*GetUsageLimitStatusAndActiveGrantsResponse)(nil),                        // 12: cursor_usage.GetUsageLimitStatusAndActiveGrantsResponse
	(*GetMeRequest)(nil),                                                      // 13: cursor_usage.GetMeRequest
	(*GetMeResponse)(nil),                                                     // 14: cursor_usage.GetMeResponse
	(*GetUsageLimitPolicyStatusRequest)(nil),                                  // 15: cursor_usage.GetUsageLimitPolicyStatusRequest
	(*GetUsageLimitPolicyStatusResponse)(nil),                                 // 16: cursor_usage.GetUsageLimitPolicyStatusResponse
	(*GetCurrentPeriodUsageResponse_PlanUsage)(nil),                           // 17: cursor_usage.GetCurrentPeriodUsageResponse.PlanUsage
	(*GetCurrentPeriodUsageResponse_SpendLimitUsage)(nil),                     // 18: cursor_usage.GetCurrentPeriodUsageResponse.SpendLimitUsage
	(*GetCurrentPeriodUsageResponse_FreeBestOfNPromotion)(nil),                // 19: cursor_usage.GetCurrentPeriodUsageResponse.FreeBestOfNPromotion
	(*GetAggregatedUsageEventsResponse_ModelUsageAggregation)(nil),            // 20: cursor_usage.GetAggregatedUsageEventsResponse.ModelUsageAggregation
	(*GetUsageLimitStatusAndActiveGrantsResponse_UsageLimitPolicyStatus)(nil), // 21: cursor_usage.GetUsageLimitStatusAndActiveGrantsResponse.UsageLimitPolicyStatus
	nil, // 22: cursor_usage.GetUsageLimitStatusAndActiveGrantsResponse.UsageLimitPolicyStatus.FeaturesEntry
	nil, // 23: cursor_usage.GetUsageLimitPolicyStatusResponse.FeaturesEntry
}
var file_cursor_usage_proto_depIdxs = []int32{
	17, // 0: cursor_usage.GetCurrentPeriodUsageResponse.plan_usage:type_name -> cursor_usage.GetCurrentPeriodUsageResponse.PlanUsage
	18, // 1: cursor_usage.GetCurrentPeriodUsageResponse.spend_limit_usage:type_name -> cursor_usage.GetCurrentPeriodUsageResponse.SpendLimitUsage
	19, // 2: cursor_usage.GetCurrentPeriodUsageResponse.free_best_of_n_promotion:type_name -> cursor_usage.GetCurrentPeriodUsageResponse.FreeBestOfNPromotion
	20, // 3: cursor_usage.GetAggregatedUsageEventsResponse.aggregations:type_name -> cursor_usage.GetAggregatedUsageEventsResponse.ModelUsageAggregation
	21, // 4: cursor_usage.GetUsageLimitStatusAndActiveGrantsResponse.usage_limit_policy_status:type_name -> cursor_usage.GetUsageLimitStatusAndActiveGrantsResponse.UsageLimitPolicyStatus
	10, // 5: cursor_usage.GetUsageLimitStatusAndActiveGrantsResponse.active_grants:type_name -> cursor_usage.ActiveCreditGrant
	23, // 6: cursor_usage.GetUsageLimitPolicyStatusResponse.features:type_name -> cursor_usage.GetUsageLimitPolicyStatusResponse.FeaturesEntry
	22, // 7: cursor_usage.GetUsageLimitStatusAndActiveGrantsResponse.UsageLimitPolicyStatus.features:type_name -> cursor_usage.GetUsageLimitStatusAndActiveGrantsResponse.UsageLimitPolicyStatus.FeaturesEntry
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_cursor_usage_proto_init() }
func file_cursor_usage_proto_init() {
	if File_cursor_usage_proto != nil {
		return
	}
	file_cursor_usage_proto_msgTypes[0].OneofWrappers = []any{}
	file_cursor_usage_proto_msgTypes[1].OneofWrappers = []any{}
	file_cursor_usage_proto_msgTypes[2].OneofWrappers = []any{}
	file_cursor_usage_proto_msgTypes[4].OneofWrappers = []any{}
	file_cursor_usage_proto_msgTypes[5].OneofWrappers = []any{}
	file_cursor_usage_proto_msgTypes[8].OneofWrappers = []any{}
	file_cursor_usage_proto_msgTypes[9].OneofWrappers = []any{}
	file_cursor_usage_proto_msgTypes[10].OneofWrappers = []any{}
	file_cursor_usage_proto_msgTypes[13].OneofWrappers = []any{}
	file_cursor_usage_proto_msgTypes[14].OneofWrappers = []any{}
	file_cursor_usage_proto_msgTypes[16].OneofWrappers = []any{}
	file_cursor_usage_proto_msgTypes[17].OneofWrappers = []any{}
	file_cursor_usage_proto_msgTypes[18].OneofWrappers = []any{}
	file_cursor_usage_proto_msgTypes[20].OneofWrappers = []any{}
	file_cursor_usage_proto_msgTypes[21].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cursor_usage_proto_rawDesc), len(file_cursor_usage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cursor_usage_proto_goTypes,
		DependencyIndexes: file_cursor_usage_proto_depIdxs,
		MessageInfos:      file_cursor_usage_proto_msgTypes,
	}.Build()
	File_cursor_usage_proto = out.File
	file_cursor_usage_proto_goTypes = nil
	file_cursor_usage_proto_depIdxs = nil
}
